=== Mazin04/3aEvalucionPractica/DTD/autores.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT autores (autor)*>
<!ELEMENT autor (id, nombre, ano_nacimiento, estilo)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ano_nacimiento (#PCDATA)>
<!ELEMENT estilo (#PCDATA)>

=== Mazin04/3aEvalucionPractica/DTD/autores.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./CSS/autores.css"?>
<!DOCTYPE autores SYSTEM "autores.dtd">

<autores>
    <autor>
        <id>1</id>
        <nombre>Pablo Picasso</nombre>
        <ano_nacimiento>1881</ano_nacimiento>
        <estilo>Cubismo</estilo>
    </autor>
    <autor>
        <id>5</id>
        <nombre>Ulpiano Checa</nombre>
        <ano_nacimiento>1860</ano_nacimiento>
        <estilo>Pintura</estilo>
    </autor>
</autores>
