=== Mazin04/3aEvalucionPractica/DTD/obras.dtd
<!ELEMENT obras (obra+)>
<!ELEMENT obra (id,nombre,autor,precio,altura,peso,num_piezas,descripcion,tecnica?,galeria,material?)>
<!ATTLIST obra tipo NMTOKEN #REQUIRED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #FIXED "â‚¬"><!ELEMENT altura (#PCDATA)><!ATTLIST altura longitud NMTOKEN #FIXED "m"><!ELEMENT peso (#PCDATA)><!ATTLIST peso unidad NMTOKEN #FIXED "t">
<!ELEMENT num_piezas (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tecnica (#PCDATA)>
<!ELEMENT galeria (#PCDATA)>
<!ELEMENT material (#PCDATA)>

=== Mazin04/3aEvalucionPractica/DTD/obras.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./CSS/escultura.css"?>
<!DOCTYPE obras SYSTEM "obras.dtd">

<obras>
    <obra tipo="Pictórica">
        <id>001</id>
        <nombre>Guernica</nombre>
        <autor>Pablo Picasso</autor>
        <precio moneda="€">1000</precio>
        <altura longitud="m">5</altura>
        <peso unidad="t">2</peso>
        <num_piezas>5</num_piezas>
        <descripcion>Cuadro guerra civil</descripcion>
        <tecnica>Óleo</tecnica>
        <galeria>Galeria JWD</galeria>
    </obra>
    <obra tipo="Pictórica">
        <id>002</id>
        <nombre>La Vie</nombre>
        <autor>Pablo Picasso</autor>
        <precio moneda="€">200</precio>
        <altura longitud="m">1</altura>
        <peso unidad="t">1</peso>
        <num_piezas>1</num_piezas>
        <descripcion>óleo</descripcion>
        <tecnica>Óleo</tecnica>
        <galeria>Galeria JWD</galeria>
    </obra>
    <obra tipo="Pictórica">
        <id>003</id>
        <nombre>El Sueño</nombre>
        <autor>Pablo Picasso</autor>
        <precio moneda="€">300</precio>
        <altura longitud="m">1.3</altura>
        <peso unidad="t">1</peso>
        <num_piezas>1</num_piezas>
        <descripcion>óleo</descripcion>
        <tecnica>Óleo</tecnica>
        <galeria>Galeria JWD</galeria>
    </obra>
    <obra tipo="Pictórica">
        <id>004</id>
        <nombre>Retrato de Dora Maar</nombre>
        <autor>Pablo Picasso</autor>
        <precio moneda="€">400</precio>
        <altura longitud="m">1</altura>
        <peso unidad="t">0.8</peso>
        <num_piezas>1</num_piezas>
        <descripcion>óleo</descripcion>
        <tecnica>Óleo</tecnica>
        <galeria>Galeria JWD</galeria>
    </obra>
    <obra tipo="Escultura">
        <id>005</id>
        <nombre>El piel roja</nombre>
        <autor>Ulpiano Checa</autor>
        <precio moneda="€">350</precio>
        <altura longitud="m">1</altura>
        <peso unidad="t">0.8</peso>
        <num_piezas>1</num_piezas>
        <descripcion>Escultura</descripcion>
        <material>Bronce</material>
        <galeria>Galeria JWD</galeria>
    </obra>
</obras>
